# Generated by Django 3.2.8 on 2021-10-27 10:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('phone_number', models.CharField(max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
